//! Generates the typed App Registry GraphQL client from the vendored
//! subgraph schema and this crate's `.graphql` operation documents.
//!
//! The committed `graphql/schema.graphql` is regenerated by `cargo run -p
//! generate-api-catalog` from the canonical `app-registry-api` service repo
//! (see that tool's `app_registry_spec.rs` for why — the schema isn't
//! hand-maintained in a "-specification" repo the way the REST domains' are).
//! Every other `.graphql` file in that directory is one operation document;
//! this build step is hermetic and never accesses the network.

use std::{env, fs, path::Path};

use graphql_client_codegen::{
    CodegenMode, GraphQLClientCodegenOptions, generate_module_token_stream,
};
use syn::visit_mut::{self, VisitMut};

/// Marks every unset (`None`) optional field on a generated *input* struct
/// (the `Variables` struct and the input objects nested in it) as omitted
/// from the request instead of serialized as an explicit `null`.
///
/// In GraphQL an omitted input field and an explicit `null` are different
/// things — e.g. `distributionType` is documented as "omit to leave
/// unchanged", and the manifest `redirectUris` sync relies on an absent key
/// leaving the remote allowlist alone while `[]` clears it — so an unset
/// `Option` must not turn into `null`.
///
/// `graphql_client_codegen`'s own `skip_serializing_none` option is not used
/// because it also applies to *response* structs, which would make the CLI's
/// JSON output drop `null` fields it has always printed. Input structs are
/// told apart from response structs by deriving `Serialize` without
/// `PartialEq` (see `set_response_derives` / `set_variables_derives` below).
struct OmitNoneInInputs;

impl VisitMut for OmitNoneInInputs {
    fn visit_item_struct_mut(&mut self, item: &mut syn::ItemStruct) {
        if derives(item, "Serialize")
            && !derives(item, "PartialEq")
            && let syn::Fields::Named(fields) = &mut item.fields
        {
            for field in &mut fields.named {
                if is_option(&field.ty) {
                    field.attrs.push(syn::parse_quote!(
                        #[serde(skip_serializing_if = "Option::is_none")]
                    ));
                }
            }
        }
        visit_mut::visit_item_struct_mut(self, item);
    }
}

fn derives(item: &syn::ItemStruct, name: &str) -> bool {
    let mut found = false;
    for attr in item.attrs.iter().filter(|a| a.path().is_ident("derive")) {
        let _ = attr.parse_nested_meta(|meta| {
            if meta
                .path
                .segments
                .last()
                .is_some_and(|seg| seg.ident == name)
            {
                found = true;
            }
            Ok(())
        });
    }
    found
}

fn is_option(ty: &syn::Type) -> bool {
    matches!(ty, syn::Type::Path(path)
        if path.path.segments.last().is_some_and(|seg| seg.ident == "Option"))
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let graphql_dir = Path::new("graphql");
    let schema_path = graphql_dir.join("schema.graphql");
    // Directory-level, not just the schema file and each currently-existing
    // operation doc below: a `rerun-if-changed` only watches paths that
    // exist when this script runs, so without this a newly *added*
    // `graphql/*.graphql` file wouldn't trigger a rebuild until some other
    // watched file also changed.
    println!("cargo:rerun-if-changed={}", graphql_dir.display());
    println!("cargo:rerun-if-changed={}", schema_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut query_paths: Vec<_> = fs::read_dir(graphql_dir)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension().and_then(|ext| ext.to_str()) == Some("graphql")
                && path.file_name().and_then(|name| name.to_str()) != Some("schema.graphql")
        })
        .collect();
    query_paths.sort();

    let mut tokens = proc_macro2::TokenStream::new();
    for query_path in &query_paths {
        println!("cargo:rerun-if-changed={}", query_path.display());

        let mut options = GraphQLClientCodegenOptions::new(CodegenMode::Cli);
        options.set_module_visibility(syn1::parse_str("pub")?);
        // Bare `Serialize`/`Deserialize`, not qualified paths: every
        // generated module already has `use serde::{Serialize,
        // Deserialize};` in scope, and a qualified path here would dodge
        // graphql_client_codegen's own dedup filter (an exact string match
        // against `"Serialize"`/`"Deserialize"`) that keeps them off enum
        // types, which already get hand-written impls — a qualified path
        // collides with those impls instead of being skipped.
        options.set_response_derives("Clone,Debug,PartialEq,Serialize".to_owned());
        // `Deserialize` on the input/variable side isn't needed by
        // `client.rs` itself — every `ApplicationClient` method takes a
        // typed input struct directly, not `serde_json::Value` — it's kept
        // so this crate's own tests can build inputs from `json!(...)`
        // literals instead of fully-spelled-out struct literals.
        options.set_variables_derives("Clone,Debug,Deserialize".to_owned());
        options.set_custom_scalars_module(syn1::parse_str("crate::scalars")?);

        let generated = generate_module_token_stream(query_path.clone(), &schema_path, options)
            .map_err(|e| format!("codegen failed for {}: {e}", query_path.display()))?;
        tokens.extend(generated);
    }

    let mut ast: syn::File = syn::parse2(tokens)?;
    OmitNoneInInputs.visit_file_mut(&mut ast);
    fs::write(
        Path::new(&env::var("OUT_DIR")?).join("codegen.rs"),
        prettyplease::unparse(&ast),
    )?;
    Ok(())
}
