//! Generates the typed App Registry GraphQL client from the vendored
//! subgraph schema and this crate's `.graphql` operation documents.
//!
//! The committed `graphql/schema.graphql` is regenerated by `cargo run -p
//! generate-api-catalog` from the canonical `app-registry-api` service repo
//! (see that tool's `app_registry_spec.rs` for why — the schema isn't
//! hand-maintained in a "-specification" repo the way the REST domains' are).
//! Every other `.graphql` file in that directory is one operation document;
//! this build step is hermetic and never accesses the network.

use std::{env, fs, path::Path};

use graphql_client_codegen::{
    CodegenMode, GraphQLClientCodegenOptions, generate_module_token_stream,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let graphql_dir = Path::new("graphql");
    let schema_path = graphql_dir.join("schema.graphql");
    println!("cargo:rerun-if-changed={}", schema_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut query_paths: Vec<_> = fs::read_dir(graphql_dir)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension().and_then(|ext| ext.to_str()) == Some("graphql")
                && path.file_name().and_then(|name| name.to_str()) != Some("schema.graphql")
        })
        .collect();
    query_paths.sort();

    let mut tokens = proc_macro2::TokenStream::new();
    for query_path in &query_paths {
        println!("cargo:rerun-if-changed={}", query_path.display());

        let mut options = GraphQLClientCodegenOptions::new(CodegenMode::Cli);
        options.set_module_visibility(syn1::parse_str("pub")?);
        // Bare `Serialize`/`Deserialize`, not qualified paths: every
        // generated module already has `use serde::{Serialize,
        // Deserialize};` in scope, and a qualified path here would dodge
        // graphql_client_codegen's own dedup filter (an exact string match
        // against `"Serialize"`/`"Deserialize"`) that keeps them off enum
        // types, which already get hand-written impls — a qualified path
        // collides with those impls instead of being skipped.
        options.set_response_derives("Clone,Debug,PartialEq,Serialize".to_owned());
        // `Deserialize` on the input/variable side lets `client.rs` accept
        // `serde_json::Value` at its own public boundary (unchanged from
        // today, so no command-layer call site needs to change) and convert
        // to a typed input via `serde_json::from_value` before sending —
        // catching a malformed input at that conversion instead of a
        // rejected GraphQL request.
        options.set_variables_derives("Clone,Debug,Deserialize".to_owned());
        options.set_custom_scalars_module(syn1::parse_str("crate::scalars")?);

        let generated = generate_module_token_stream(query_path.clone(), &schema_path, options)
            .map_err(|e| format!("codegen failed for {}: {e}", query_path.display()))?;
        tokens.extend(generated);
    }

    let ast = syn::parse2(tokens)?;
    fs::write(
        Path::new(&env::var("OUT_DIR")?).join("codegen.rs"),
        prettyplease::unparse(&ast),
    )?;
    Ok(())
}
