//! Generates the typed Shopping API client from the vendored OpenAPI 3.0 spec.
//!
//! The committed `openapi/shopping.oas3.json` is regenerated by `cargo run -p
//! generate-api-catalog` from the canonical `gdcorp-platform/shopping.ucp-specification`
//! contract. This build step is hermetic and never accesses the network.

use std::{env, fs, path::Path};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let spec_path = "openapi/shopping.oas3.json";
    println!("cargo:rerun-if-changed={spec_path}");
    println!("cargo:rerun-if-changed=build.rs");

    let spec_text = fs::read_to_string(spec_path)?;
    let spec: openapiv3::OpenAPI = serde_json::from_str(&spec_text)?;
    let mut settings = progenitor::GenerationSettings::new();
    settings.with_interface(progenitor::InterfaceStyle::Builder);
    settings.with_derive("schemars::JsonSchema");
    let mut generator = progenitor::Generator::new(&settings);
    let tokens = generator.generate_tokens(&spec)?;
    let ast = syn::parse2(tokens)?;
    fs::write(
        Path::new(&env::var("OUT_DIR")?).join("codegen.rs"),
        prettyplease::unparse(&ast),
    )?;
    Ok(())
}
